export default function Home() {
  return (
    <div>
      <h1>Welcome to your new Mantine app!</h1>
      <p>
        This is a simple page generated by Mantine CLI. You can start building
        your app by editing this file.
      </p>
    </div>
  );
}
