export default function About() {
  return (
    <div>
      <h1>About</h1>
      <p>
        This is a simple page generated by Mantine CLI. You can start building
        your app by editing this file.
      </p>
    </div>
  );
}
